name: 'Renovate Review'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      renovate: ${{ steps.filter.outputs.renovate }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      # For pull requests it's not necessary to checkout the code
      - name: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            renovate:
              - '.renovate.json5'

  renovate-review:
    needs: changes
    if: ${{ needs.changes.outputs.renovate == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: renovate-config-validator
        uses: rinchsan/renovate-config-validator@8cf44ae5646f111f838a03ac7ebd4e1c1f9be983 # v0.2.1
        with:
          pattern: .renovate.json5
